# Generated by Django 5.2.5 on 2025-11-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeros',
            fields=[
                ('rut_enfermero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'enfermeros',
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=4, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salas',
            },
        ),
        migrations.CreateModel(
            name='Tens',
            fields=[
                ('rut_tens', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'tens',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_turno', models.DateField(blank=True, null=True)),
                ('dia_semana', models.CharField(blank=True, max_length=9, null=True)),
                ('hora_turno', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'turnos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=15, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=100, null=True)),
                ('rol', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(blank=True, max_length=200, null=True)),
                ('examenes_previos', models.CharField(blank=True, db_column='Examenes_Previos', max_length=1000, null=True)),
                ('examenes_pendientes', models.CharField(blank=True, db_column='Examenes_pendientes', max_length=1000, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_paciente', models.ForeignKey(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TurnosApp.pacientes')),
            ],
            options={
                'db_table': 'historial_medico',
            },
        ),
        migrations.AddField(
            model_name='pacientes',
            name='id_sala',
            field=models.ForeignKey(blank=True, db_column='id_sala', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TurnosApp.salas'),
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('dia_semana', models.CharField(blank=True, max_length=9, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('rut_enfermero', models.ForeignKey(blank=True, db_column='rut_enfermero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TurnosApp.enfermeros')),
                ('rut_tens', models.ForeignKey(blank=True, db_column='rut_tens', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TurnosApp.tens')),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('completada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TurnosApp.usuarios')),
            ],
            options={
                'db_table': 'tareas',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut_administrador', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
    ]
